---
#arquivo padrão com as configurações de ambiente, banco e login
url: "http://192.168.99.100:8080"
database: 
  host: "192.168.99.100"
  dbname: "ninjaflix"
  user: "postgres"
  password: "qaninja"
users:
  cat_manager:
    email: "tony@stark.com"
    pass: "pwd123"